exports.datas = [{
	"company": "呼伦贝尔中超房地产开发有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "呼伦贝尔中超房地产开发有限公司",
	"person": "王玉光",
	"relation": "股东"
}, {
	"company": "中草生态农业股份有限公司",
	"person": "戴青",
	"relation": "股东"
}, {
	"company": "中正天泰投资管理有限公司",
	"person": "青秋华",
	"relation": "股东"
}, {
	"company": "中汇联国际投资有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "包头北方智德置业有限责任公司",
	"person": "姜传军",
	"relation": "股东"
}, {
	"company": "习水县中新矿业有限公司",
	"person": "王继香",
	"relation": "股东"
}, {
	"company": "习水县中新矿业有限公司",
	"person": "郭英",
	"relation": "股东"
}, {
	"company": "贵州省习水县龙涛矿业有限公司",
	"person": "王继香",
	"relation": "股东"
}, {
	"company": "贵州省习水县龙涛矿业有限公司",
	"person": "郭英",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "俞宏",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "孙贵龙",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "戴树莘",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "朱荣新",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "王文斌",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "苏玉玲",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "石玉海",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "王新杰",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "张霭宏",
	"relation": "股东"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "孟岚",
	"relation": "股东"
}, {
	"company": "北京吉辰达文化传播有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "北京吉辰达文化传播有限公司",
	"person": "吴子斌",
	"relation": "股东"
}, {
	"company": "北京吉辰达文化传播有限公司",
	"person": "孟岚",
	"relation": "股东"
}, {
	"company": "北京吉辰达文化传播有限公司",
	"person": "吉雅岚",
	"relation": "股东"
}, {
	"company": "通辽市金港物流集团有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "通辽市金港物流集团有限公司",
	"person": "李佳蓉",
	"relation": "股东"
}, {
	"company": "黑龙江蒙龙经贸有限公司",
	"person": "李佳蓉",
	"relation": "股东"
}, {
	"company": "黑龙江蒙龙经贸有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "北京汉华大地科技开发有限公司",
	"person": "肖红",
	"relation": "股东"
}, {
	"company": "北京汉华大地科技开发有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "北京汉华大地科技开发有限公司",
	"person": "钟桂平",
	"relation": "股东"
}, {
	"company": "中鑫泰新材料有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "中鑫泰新材料有限公司",
	"person": "盛新光",
	"relation": "股东"
}, {
	"company": "易县永安陵园有限公司",
	"person": "王会春",
	"relation": "股东"
}, {
	"company": "易县永安陵园有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "易县永安陵园有限公司",
	"person": "王忠明",
	"relation": "股东"
}, {
	"company": "呼伦贝尔市顺新煤炭经销有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "呼伦贝尔市顺新煤炭经销有限公司",
	"person": "陈丽卫",
	"relation": "股东"
}, {
	"company": "内蒙古英伦畜牧业科技发展有限公司",
	"person": "刘及东",
	"relation": "股东"
}, {
	"company": "内蒙古英伦畜牧业科技发展有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "内蒙古中景房地产开发有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "内蒙古中景房地产开发有限公司",
	"person": "王瑞凤",
	"relation": "股东"
}, {
	"company": "呼伦贝尔盛世嘉和物业有限公司",
	"person": "李佳蓉",
	"relation": "股东"
}, {
	"company": "呼伦贝尔盛世嘉和物业有限公司",
	"person": "王坚峰",
	"relation": "股东"
}, {
	"company": "通辽市金港物业服务有限公司",
	"person": "李佳蓉",
	"relation": "股东"
}, {
	"company": "通辽市金港物业服务有限公司",
	"person": "王忠明",
	"relation": "股东"
}, {
	"company": "通辽市金港房地产开发有限公司",
	"person": "王忠明",
	"relation": "股东"
}, {
	"company": "北京基洛夫化肥有限公司",
	"person": "李佳蓉",
	"relation": "股东"
}, {
	"company": "北京基洛夫化肥有限公司",
	"person": "贺妍",
	"relation": "股东"
}, {
	"company": "喀什天富国际贸易有限公司",
	"person": "方柏",
	"relation": "法人代表"
}, {
	"company": "鄂温克旗信成信用担保有限公司",
	"person": "史军",
	"relation": "法人代表"
}, {
	"company": "呼伦贝尔中超房地产开发有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "中债商业保理有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "中草生态农业股份有限公司",
	"person": "刘及东",
	"relation": "法人代表"
}, {
	"company": "中正天泰投资管理有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "上海亚太国际商品交易服务有限公司",
	"person": "董朝斌",
	"relation": "法人代表"
}, {
	"company": "中汇联国际投资有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "中汇联金融服务天津有限公司",
	"person": "于权",
	"relation": "法人代表"
}, {
	"company": "中汇联投资浙江有限公司",
	"person": "于权",
	"relation": "法人代表"
}, {
	"company": "中汇联珠海金融服务有限公司",
	"person": "于权",
	"relation": "法人代表"
}, {
	"company": "中汇联国际投资新疆有限公司",
	"person": "于权",
	"relation": "法人代表"
}, {
	"company": "菠萝海创新科技北京有限公司",
	"person": "马秀丽",
	"relation": "法人代表"
}, {
	"company": "包头北方智德置业有限责任公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "习水县中新矿业有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "贵州省习水县龙涛矿业有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "北京吉辰达文化传播有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "通辽市金港物流集团有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "黑龙江蒙龙经贸有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "北京汉华大地科技开发有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "中鑫泰新材料有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "秦皇岛华瀛磷酸有限公司",
	"person": "王坚峰",
	"relation": "法人代表"
}, {
	"company": "秦皇岛市瑞驰商贸有限公司",
	"person": "冯民",
	"relation": "法人代表"
}, {
	"company": "易县永安陵园有限公司",
	"person": "王玉光",
	"relation": "法人代表"
}, {
	"company": "保定华夏物业有限公司",
	"person": "王会春",
	"relation": "法人代表"
}, {
	"company": "呼伦贝尔市顺新煤炭经销有限公司",
	"person": "陈丽卫",
	"relation": "法人代表"
}, {
	"company": "内蒙古英伦畜牧业科技发展有限公司",
	"person": "李佳蓉",
	"relation": "法人代表"
}, {
	"company": "内蒙古中景房地产开发有限公司",
	"person": "王瑞凤",
	"relation": "法人代表"
}, {
	"company": "呼伦贝尔盛世嘉和物业有限公司",
	"person": "刘宏",
	"relation": "法人代表"
}, {
	"company": "满洲里基洛夫石化有限公司",
	"person": "李佳蓉",
	"relation": "法人代表"
}, {
	"company": "呼伦贝尔中超房地产开发有限公司满洲里分公司",
	"person": "刘宏",
	"relation": "法人代表"
}, {
	"company": "通辽市金港物业服务有限公司",
	"person": "李佳蓉",
	"relation": "法人代表"
}, {
	"company": "通辽市金港房地产开发有限公司",
	"person": "王忠明",
	"relation": "法人代表"
}, {
	"company": "通辽市基洛夫农业生产资料有限公司",
	"person": "王忠明",
	"relation": "法人代表"
}, {
	"company": "北京基洛夫化肥有限公司",
	"person": "李佳蓉",
	"relation": "法人代表"
}, {
	"company": "喀什天富国际贸易有限公司",
	"person": "中信夹层投资中心",
	"relation": "关联公司"
}, {
	"company": "喀什天富国际贸易有限公司",
	"person": "李佳蓉",
	"relation": "监事"
}, {
	"company": "喀什天富国际贸易有限公司",
	"person": "方柏",
	"relation": "执行董事兼经理"
}, {
	"company": "鄂温克旗信成信用担保有限公司",
	"person": "何淑慧",
	"relation": "监事"
}, {
	"company": "鄂温克旗信成信用担保有限公司",
	"person": "史军",
	"relation": "经理"
}, {
	"company": "呼伦贝尔中超房地产开发有限公司",
	"person": "杨舒雅",
	"relation": "监事"
}, {
	"company": "呼伦贝尔中超房地产开发有限公司",
	"person": "王坚峰",
	"relation": "经理"
}, {
	"company": "中债商业保理有限公司",
	"person": "李佳蓉",
	"relation": "监事"
}, {
	"company": "中债商业保理有限公司",
	"person": "王坚峰",
	"relation": "执行董事兼总经理"
}, {
	"company": "中草生态农业股份有限公司",
	"person": "王坚峰",
	"relation": "董事长"
}, {
	"company": "中草生态农业股份有限公司",
	"person": "刘及东",
	"relation": "董事"
}, {
	"company": "中草生态农业股份有限公司",
	"person": "叶和云",
	"relation": "董事"
}, {
	"company": "中草生态农业股份有限公司",
	"person": "杜建材",
	"relation": "董事"
}, {
	"company": "中草生态农业股份有限公司",
	"person": "戴青",
	"relation": "董事"
}, {
	"company": "中草生态农业股份有限公司",
	"person": "甄茁",
	"relation": "监事"
}, {
	"company": "中草生态农业股份有限公司",
	"person": "韩宇",
	"relation": "监事"
}, {
	"company": "中草生态农业股份有限公司",
	"person": "邓丽丽",
	"relation": "监事"
}, {
	"company": "中正天泰投资管理有限公司",
	"person": "青秋华",
	"relation": "监事"
}, {
	"company": "中正天泰投资管理有限公司",
	"person": "王坚峰",
	"relation": "执行董事"
}, {
	"company": "中正天泰投资管理有限公司",
	"person": "李高冰",
	"relation": "经理"
}, {
	"company": "上海亚太国际商品交易服务有限公司",
	"person": "白鹤林",
	"relation": "董事长"
}, {
	"company": "上海亚太国际商品交易服务有限公司",
	"person": "蒋岩松",
	"relation": "董事"
}, {
	"company": "上海亚太国际商品交易服务有限公司",
	"person": "杨家斌",
	"relation": "董事"
}, {
	"company": "上海亚太国际商品交易服务有限公司",
	"person": "薛文祥",
	"relation": "董事"
}, {
	"company": "上海亚太国际商品交易服务有限公司",
	"person": "朱定法",
	"relation": "监事"
}, {
	"company": "上海亚太国际商品交易服务有限公司",
	"person": "董朝斌",
	"relation": "董事兼总经理"
}, {
	"company": "中汇联国际投资有限公司",
	"person": "王坚峰",
	"relation": "董事长"
}, {
	"company": "中汇联国际投资有限公司",
	"person": "于权",
	"relation": "董事"
}, {
	"company": "中汇联国际投资有限公司",
	"person": "李佳蓉",
	"relation": "董事"
}, {
	"company": "中汇联国际投资有限公司",
	"person": "贺妍",
	"relation": "监事"
}, {
	"company": "中汇联国际投资有限公司",
	"person": "于权",
	"relation": "经理"
}, {
	"company": "中汇联金融服务天津有限公司",
	"person": "于权",
	"relation": "董事长兼经理"
}, {
	"company": "中汇联金融服务天津有限公司",
	"person": "李佳蓉",
	"relation": "董事"
}, {
	"company": "中汇联金融服务天津有限公司",
	"person": "王坚峰",
	"relation": "董事"
}, {
	"company": "中汇联金融服务天津有限公司",
	"person": "贺妍",
	"relation": "监事"
}, {
	"company": "中汇联投资浙江有限公司",
	"person": "于权",
	"relation": "董事长"
}, {
	"company": "中汇联投资浙江有限公司",
	"person": "王坚峰",
	"relation": "董事"
}, {
	"company": "中汇联投资浙江有限公司",
	"person": "李佳蓉",
	"relation": "董事"
}, {
	"company": "中汇联投资浙江有限公司",
	"person": "沈建芬",
	"relation": "董事"
}, {
	"company": "中汇联投资浙江有限公司",
	"person": "张洪海",
	"relation": "监事"
}, {
	"company": "中汇联投资浙江有限公司",
	"person": "王涤",
	"relation": "董事兼总经理"
}, {
	"company": "中汇联珠海金融服务有限公司",
	"person": "鲁志云",
	"relation": "不详"
}, {
	"company": "中汇联珠海金融服务有限公司",
	"person": "于权",
	"relation": "不详"
}, {
	"company": "中汇联珠海金融服务有限公司",
	"person": "王立兵",
	"relation": "不详"
}, {
	"company": "中汇联珠海金融服务有限公司",
	"person": "施宇青",
	"relation": "不详"
}, {
	"company": "中汇联国际投资新疆有限公司",
	"person": "于权",
	"relation": "执行董事"
}, {
	"company": "中汇联国际投资新疆有限公司",
	"person": "樊朝娟",
	"relation": "监事"
}, {
	"company": "中汇联国际投资新疆有限公司",
	"person": "那兵",
	"relation": "经理"
}, {
	"company": "菠萝海创新科技北京有限公司",
	"person": "马秀丽",
	"relation": "执行董事兼经理"
}, {
	"company": "菠萝海创新科技北京有限公司",
	"person": "齐吉安",
	"relation": "监事"
}, {
	"company": "包头北方智德置业有限责任公司",
	"person": "王坚峰",
	"relation": "执行董事兼总经理"
}, {
	"company": "包头北方智德置业有限责任公司",
	"person": "贺妍",
	"relation": "监事"
}, {
	"company": "习水县中新矿业有限公司",
	"person": "王坚峰",
	"relation": "执行董事"
}, {
	"company": "习水县中新矿业有限公司",
	"person": "郭英",
	"relation": "监事"
}, {
	"company": "贵州省习水县龙涛矿业有限公司",
	"person": "王坚峰",
	"relation": "执行董事"
}, {
	"company": "贵州省习水县龙涛矿业有限公司",
	"person": "王继香",
	"relation": "监事"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "王坚峰",
	"relation": "董事长"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "卓蕊",
	"relation": "董事"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "俞宏",
	"relation": "董事兼总经理"
}, {
	"company": "北京基洛夫投资有限公司",
	"person": "王文斌",
	"relation": "监事"
}, {
	"company": "北京吉辰达文化传播有限公司",
	"person": "王坚峰",
	"relation": "董事长"
}, {
	"company": "北京吉辰达文化传播有限公司",
	"person": "吴子斌",
	"relation": "董事"
}, {
	"company": "北京吉辰达文化传播有限公司",
	"person": "孟岚",
	"relation": "监事"
}, {
	"company": "北京吉辰达文化传播有限公司",
	"person": "吉雅岚",
	"relation": "董事兼总经理"
}, {
	"company": "通辽市金港物流集团有限公司",
	"person": "王坚峰",
	"relation": "其他人员"
}, {
	"company": "通辽市金港物流集团有限公司",
	"person": "李佳蓉",
	"relation": "其他人员"
}, {
	"company": "黑龙江蒙龙经贸有限公司",
	"person": "李佳蓉",
	"relation": "监事"
}, {
	"company": "黑龙江蒙龙经贸有限公司",
	"person": "王坚峰",
	"relation": "执行董事"
}, {
	"company": "北京汉华大地科技开发有限公司",
	"person": "王坚峰",
	"relation": "董事长"
}, {
	"company": "北京汉华大地科技开发有限公司",
	"person": "肖红",
	"relation": "董事兼总经理"
}, {
	"company": "北京汉华大地科技开发有限公司",
	"person": "钟桂平",
	"relation": "董事"
}, {
	"company": "北京汉华大地科技开发有限公司",
	"person": "李佳蓉",
	"relation": "监事"
}, {
	"company": "中鑫泰新材料有限公司",
	"person": "王坚峰",
	"relation": "执行董事兼经理"
}, {
	"company": "中鑫泰新材料有限公司",
	"person": "盛新光",
	"relation": "监事"
}, {
	"company": "秦皇岛华瀛磷酸有限公司",
	"person": "王坚峰",
	"relation": "董事长"
}, {
	"company": "秦皇岛华瀛磷酸有限公司",
	"person": "曹涛",
	"relation": "副董事长"
}, {
	"company": "秦皇岛华瀛磷酸有限公司",
	"person": "陈世东",
	"relation": "董事"
}, {
	"company": "秦皇岛华瀛磷酸有限公司",
	"person": "武四海",
	"relation": "董事"
}, {
	"company": "秦皇岛华瀛磷酸有限公司",
	"person": "邱士军",
	"relation": "董事"
}, {
	"company": "秦皇岛华瀛磷酸有限公司",
	"person": "赵会田",
	"relation": "董事"
}, {
	"company": "秦皇岛华瀛磷酸有限公司氟盐分公司",
	"person": "冯民",
	"relation": ""
}, {
	"company": "秦皇岛市瑞驰商贸有限公司",
	"person": "冯民",
	"relation": "董事长兼总经理"
}, {
	"company": "秦皇岛市瑞驰商贸有限公司",
	"person": "付军",
	"relation": "董事"
}, {
	"company": "秦皇岛市瑞驰商贸有限公司",
	"person": "康志国",
	"relation": "董事"
}, {
	"company": "秦皇岛市瑞驰商贸有限公司",
	"person": "张继春",
	"relation": "监事"
}, {
	"company": "帝思帕上海贸易有限公司",
	"person": "李佳蓉",
	"relation": "监事"
}, {
	"company": "帝思帕上海贸易有限公司",
	"person": "王坚峰",
	"relation": "执行董事 "
}, {
	"company": "易县永安陵园有限公司",
	"person": "王玉光",
	"relation": "执行董事"
}, {
	"company": "易县永安陵园有限公司",
	"person": "王会春",
	"relation": "监事"
}, {
	"company": "保定华夏物业有限公司",
	"person": "王慧生",
	"relation": "监事"
}, {
	"company": "保定华夏物业有限公司",
	"person": "王会梅",
	"relation": "总经理"
}, {
	"company": "保定华夏物业有限公司",
	"person": "王会春",
	"relation": "执行董事"
}, {
	"company": "呼伦贝尔市顺新煤炭经销有限公司",
	"person": "王坚峰",
	"relation": "监事"
}, {
	"company": "呼伦贝尔市顺新煤炭经销有限公司",
	"person": "陈丽卫",
	"relation": "执行董事"
}, {
	"company": "内蒙古英伦畜牧业科技发展有限公司",
	"person": "王坚峰",
	"relation": "监事"
}, {
	"company": "内蒙古英伦畜牧业科技发展有限公司",
	"person": "刘及东",
	"relation": "监事"
}, {
	"company": "内蒙古英伦畜牧业科技发展有限公司",
	"person": "李佳蓉",
	"relation": "执行董事"
}, {
	"company": "内蒙古中景房地产开发有限公司",
	"person": "王瑞凤",
	"relation": "其他人员"
}, {
	"company": "内蒙古中景房地产开发有限公司",
	"person": "王瑞琴",
	"relation": "其他人员"
}, {
	"company": "呼伦贝尔盛世嘉和物业有限公司",
	"person": "王坚峰",
	"relation": "董事"
}, {
	"company": "呼伦贝尔盛世嘉和物业有限公司",
	"person": "刘晓芝",
	"relation": "监事"
}, {
	"company": "呼伦贝尔盛世嘉和物业有限公司",
	"person": "刘宏",
	"relation": "不详"
}, {
	"company": "呼伦贝尔盛世嘉和物业有限公司",
	"person": "祡玉喜",
	"relation": "经理"
}, {
	"company": "满洲里基洛夫石化有限公司",
	"person": "王志良",
	"relation": "监事"
}, {
	"company": "满洲里基洛夫石化有限公司",
	"person": "李佳蓉",
	"relation": "执行董事"
}, {
	"company": "呼伦贝尔中超房地产开发有限公司满洲里分公司",
	"person": "刘宏",
	"relation": ""
}, {
	"company": "通辽市金港物业服务有限公司",
	"person": "王忠明",
	"relation": "监事"
}, {
	"company": "通辽市金港物业服务有限公司",
	"person": "李佳蓉",
	"relation": "其他人员"
}, {
	"company": "通辽市金港房地产开发有限公司",
	"person": "刘庆阳",
	"relation": "监事"
}, {
	"company": "通辽市金港房地产开发有限公司",
	"person": "王忠明",
	"relation": "执行董事"
}, {
	"company": "通辽市基洛夫农业生产资料有限公司",
	"person": "王忠明",
	"relation": "其他人员"
}, {
	"company": "通辽市基洛夫农业生产资料有限公司",
	"person": "杨舒雅",
	"relation": "其他人员"
}, {
	"company": "北京基洛夫化肥有限公司",
	"person": "李佳蓉",
	"relation": "执行董事兼经理"
}, {
	"company": "北京基洛夫化肥有限公司",
	"person": "贺妍",
	"relation": "监事"
}, {
	"company": "阿拉山口恒超贸易有限公司",
	"person": "王志良",
	"relation": "股东/监事 0.25"
}, {
	"company": "阿拉山口恒超贸易有限公司",
	"person": "王忠明",
	"relation": "法人及主要经营者"
}, {
	"company": "阿拉山口恒超贸易有限公司",
	"person": "杨舒雅",
	"relation": "股东0.25"
}, {
	"company": "北京和风顺科技有限公司",
	"person": "贺妍",
	"relation": "监事"
}, {
	"company": "北京和风顺科技有限公司",
	"person": "王玉光",
	"relation": "法定代表人"
}, {
	"company": "北京兴地矿业投资有限公司",
	"person": "李佳蓉",
	"relation": "监事"
}, {
	"company": "北京兴地矿业投资有限公司",
	"person": "王坚峰",
	"relation": "法定代表人/负责人/执行事务合伙人，股东1.5%"
}, {
	"company": "北京兴地矿业投资有限公司",
	"person": "王忠明",
	"relation": "股东0.985"
}, {
	"company": "北京兴地矿业投资有限公司",
	"person": "王钟明",
	"relation": "股东99%"
}, {
	"company": "呼和浩特市正大华兴农业生产资料有限责任公司",
	"person": "王忠明",
	"relation": "股东0.6"
}, {
	"company": "呼伦贝尔市盛世嘉和物业服务有限公司",
	"person": "刘宏",
	"relation": "法定代表人"
}, {
	"company": "呼伦贝尔中超房地产开发有限公司",
	"person": "刘宏",
	"relation": "法定代表人"
}, {
	"company": "满洲里恒超经贸有限公司",
	"person": "方柏",
	"relation": "监事"
}, {
	"company": "满洲里恒超经贸有限公司",
	"person": "刘宏",
	"relation": "法定代表人/负责人/执行事务合伙人/股东/执行董事"
}, {
	"company": "满洲里恒超经贸有限公司",
	"person": "王忠明",
	"relation": "法人及主要经营者"
}, {
	"company": "首创担保",
	"person": "北京银行光明支行",
	"relation": "担保操作行"
}, {
	"company": "通辽市基洛夫农业生产资料有限公司",
	"person": "王忠明",
	"relation": "法定代表人"
}, {
	"company": "通辽市金港房地产开发有限公司",
	"person": "王忠明",
	"relation": "执行董事/法定代表人/投资者"
}, {
	"company": "通辽市金港物业服务有限公司",
	"person": "王忠明",
	"relation": "股东0.3"
}, {
	"company": "王坚峰",
	"person": "王忠明",
	"relation": "父亲"
}, {
	"company": "中新恒超实业有限公司",
	"person": "李佳蓉",
	"relation": "监事"
}, {
	"company": "中新恒超实业有限公司",
	"person": "马秀丽",
	"relation": "企业经办人"
}, {
	"company": "中新恒超实业有限公司",
	"person": "首创担保",
	"relation": "担保公司"
}, {
	"company": "中新恒超实业有限公司",
	"person": "王坚峰",
	"relation": "董事长、总经理"
}, {
	"company": "中新恒超实业有限公司",
	"person": "王志良",
	"relation": "董事"
}, {
	"company": "中新恒超实业有限公司",
	"person": "杨舒雅",
	"relation": "董事"
}]